<a href="https://colab.research.google.com/github/DolevSeren/DI-Bootcamp/blob/main/dailyexcersizeW4D1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
array_1 = np.arange(10)
array_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
my_list = [3.14, 2.17, 0, 1, 2]
my_array = np.array(my_list)
int_array = my_array.astype(int)
int_array

array([3, 2, 0, 1, 2])

In [8]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr_2d = np.random.uniform(0, 1, size=(4, 5))
arr_2d = np.round(np.random.rand(4, 5), 2)
arr_2d


array([[0.92, 0.04, 0.71, 0.35, 0.45],
       [0.57, 0.06, 0.43, 0.44, 0.33],
       [0.77, 0.57, 0.14, 0.3 , 0.83],
       [0.13, 0.31, 0.99, 0.35, 0.81]])

In [16]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
second_row = array[1]
second_row

array([20, 21, 22, 23, 24])

In [17]:
reverse_array = array_1[::-1]
reverse_array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [18]:
array_2 = np.arange(16)
reshaped_array_2 = array_2.reshape(4,4)
reshaped_array_2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
print("sum: ", np.sum(array_1))
print("average :" , np.average(array_1))

sum:  45
average : 4.5


In [21]:
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [22]:
odd_number = array_1[array_1 % 2 == 1]
odd_number

array([1, 3, 5, 7, 9])